apiVersion: v1
kind: Service
metadata:
  name: flask-k8sapi-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-k8sapi
  sessionAffinity: None
  type: LoadBalancer